name: ci
on: 
  pull_request: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9' 
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            curl \
            software-properties-common \
            git \
            && sudo rm -rf /var/lib/apt/lists/*
      - name: Install Python Lib
        run: pip3 install -r requirements.txt
      - name:
        run: |
          echo "${{ secrets.SSH_SERVER }}"
          echo "${{ secrets.SSH_SERVER }}"
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: docker ps