name: ci
on: 
  pull:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9' 
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
          build-essential \
          curl \
          software-properties-common \
          git \
          && rm -rf /var/lib/apt/lists/*
      - run: pip3 install -r requirements.txt

      - name: install python
        run: apt-get install python3.9